all: kruskaldriver
kruskaldriver: kruskaltest.cpp
	g++ -std=c++11 -o kruskaldriver kruskaltest.cpp Disjoint_Set_Definitions.cpp Linked_List_Definitions.cpp Node_Definitions.cpp Graph_Definitions.cpp
clean:
	rm kruskaltest
